# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=140)),
                ('product_description', models.CharField(max_length=1000)),
                ('product_price', models.CharField(max_length=10)),
                ('is_syndicated', models.BooleanField(default=False)),
            ],
        ),
    ]
